# Generated by Django 2.0.5 on 2018-05-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180514_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='chapter_str',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_str',
            field=models.TextField(),
        ),
    ]
