# Generated by Django 2.0.5 on 2018-05-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180514_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='chapter_str',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_str',
            field=models.CharField(max_length=30),
        ),
    ]
