# Generated by Django 2.0.5 on 2018-05-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180514_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='canonical',
            field=models.BooleanField(default=False),
        ),
    ]
