# Generated by Django 2.0.5 on 2018-05-14 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('position', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_int', models.IntegerField()),
                ('verse_int', models.IntegerField()),
                ('chapter_str', models.IntegerField()),
                ('verse_str', models.IntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workarea.Book')),
            ],
        ),
    ]
