# Generated by Django 2.0.5 on 2018-05-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workarea', '0002_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Verse',
        ),
    ]
